-- "Teknik" sekmesinde kullanıcının analiz için eklediği semboller.
-- supabase_schema.sql, supabase_schema_auth.sql ve supabase_schema_favorites.sql'den
-- SONRA, Supabase SQL Editor'de bir kez çalıştırılır. favorites ile aynı
-- desen: RLS açık, kullanıcı yalnızca kendi satırlarına erişebilir (proxy
-- server_role anahtarıyla zaten RLS'i bypass ediyor, politikalar ekstra
-- güvenlik katmanı olarak duruyor). Bu liste watchlist/favorites'ten
-- bağımsız: bildirim üretmez, sadece Teknik sekmesinde hangi sembollerin
-- analiz edileceğini belirler.

create table if not exists technical_watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  symbol text not null
);

create unique index if not exists technical_watchlist_user_symbol_key
  on technical_watchlist (user_id, symbol);

alter table technical_watchlist enable row level security;

drop policy if exists "select own technical_watchlist" on technical_watchlist;
create policy "select own technical_watchlist" on technical_watchlist
  for select using (auth.uid() = user_id);

drop policy if exists "insert own technical_watchlist" on technical_watchlist;
create policy "insert own technical_watchlist" on technical_watchlist
  for insert with check (auth.uid() = user_id);

drop policy if exists "delete own technical_watchlist" on technical_watchlist;
create policy "delete own technical_watchlist" on technical_watchlist
  for delete using (auth.uid() = user_id);
