-- Temel Analiz (Fair Value/Piotroski/Altman Z-Score) için: stocks,
-- financial_statements, stock_scores tabloları. supabase_schema.sql +
-- supabase_schema_auth.sql + supabase_schema_favorites.sql +
-- supabase_schema_technical.sql + supabase_schema_portfolio.sql +
-- supabase_schema_dividends.sql'den SONRA, Supabase SQL Editor'de bir kez
-- çalıştırılır.
--
-- ÖNEMLİ FARK: projedeki diğer tüm tablolar (watchlist, favorites,
-- portfolio_holdings, dividend_watchlist, technical_watchlist,
-- notifications) KULLANICIYA ÖZEL veridir (RLS: auth.uid() = user_id).
-- Bu üç tablo ise HERKESE AÇIK piyasa verisidir (sembol bazlı, kullanıcıya
-- özel değil) — bu yüzden RLS deseni tersine döner: anon + authenticated
-- rolleri SADECE OKUYABİLİR (politika: USING (true)), insert/update/delete
-- politikası HİÇ YOK — yazma yalnızca proxy_server'ın service_role
-- anahtarıyla olur (RLS'i zaten bypass eder, bkz. supabase_client.dart).
--
-- financial_statements.data: proxy_server/lib/yahoo_fundamentals.dart'taki
-- FinancialYear.toJson() ile birebir aynı şekli taşır (totalRevenue,
-- netIncome, freeCashFlow, operatingCashFlow, capitalExpenditure,
-- totalAssets, totalLiabilities, stockholdersEquity, currentAssets,
-- currentLiabilities, retainedEarnings, grossProfit, ebit — bazıları banka
-- gibi finans sektörü şirketlerinde null). Yahoo'nun modern
-- fundamentals-timeseries uç noktası tek tek adlandırılmış metrikler
-- döndürüyor, "bilanço/gelir tablosu/nakit akışı" diye ayrı üç yapılandırılmış
-- obje değil — bu yüzden tek bir düz JSONB kolonu kullanılıyor (üç ayrı
-- balance_sheet/income_statement/cash_flow JSONB kolonu, gerçekte
-- çekilen veriyle örtüşmeyen yapay bir ayrım olurdu).

create table if not exists stocks (
  symbol text primary key,
  company_name text not null,
  sector text,
  country text,
  currency text not null,
  last_price double precision not null,
  market_cap double precision,
  pe_ratio double precision,
  pb_ratio double precision,
  dividend_yield double precision,
  updated_at timestamptz not null default now()
);

create table if not exists financial_statements (
  id bigint generated by default as identity primary key,
  symbol text not null references stocks(symbol) on delete cascade,
  fiscal_year int not null,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create unique index if not exists financial_statements_symbol_year_key
  on financial_statements (symbol, fiscal_year);
create index if not exists financial_statements_symbol_idx
  on financial_statements (symbol);

create table if not exists stock_scores (
  symbol text primary key references stocks(symbol) on delete cascade,
  fair_value_per_share double precision,
  fair_value_upside_pct double precision,
  fair_value_error text,
  dcf_assumptions jsonb,
  altman_z_score double precision,
  altman_zone text,
  altman_error text,
  piotroski_score int,
  piotroski_max_score int,
  piotroski_criteria jsonb,
  pro_tips jsonb,
  computed_at timestamptz not null default now()
);

-- İlk sürümde error kolonları yoktu; tablo zaten oluşturulmuş olsa bile bu
-- ALTER'lar idempotent (IF NOT EXISTS) olduğundan dosyayı yeniden çalıştırmak
-- güvenli.
alter table stock_scores add column if not exists fair_value_error text;
alter table stock_scores add column if not exists altman_error text;

alter table stocks enable row level security;
alter table financial_statements enable row level security;
alter table stock_scores enable row level security;

drop policy if exists "public read stocks" on stocks;
create policy "public read stocks" on stocks
  for select to anon, authenticated using (true);

drop policy if exists "public read financial_statements" on financial_statements;
create policy "public read financial_statements" on financial_statements
  for select to anon, authenticated using (true);

drop policy if exists "public read stock_scores" on stock_scores;
create policy "public read stock_scores" on stock_scores
  for select to anon, authenticated using (true);

grant select on stocks, financial_statements, stock_scores to anon, authenticated;
