-- "Portföy" sekmesi: kullanıcının kendi pozisyonları (sembol, adet, maliyet).
-- supabase_schema.sql, supabase_schema_auth.sql, supabase_schema_favorites.sql
-- ve supabase_schema_technical.sql'den SONRA, Supabase SQL Editor'de bir kez
-- çalıştırılır. Diğerleriyle aynı desen: RLS açık, kullanıcı yalnızca kendi
-- satırlarına erişebilir (proxy server_role anahtarıyla zaten RLS'i bypass
-- ediyor, politikalar ekstra güvenlik katmanı olarak duruyor). Kullanıcı
-- başına sembol başına TEK satır — aynı sembolü tekrar eklemek mevcut
-- satırı YENİ adet/maliyetle tamamen değiştirir (ağırlıklı ortalama gibi bir
-- "birleştirme" yapmaz), bkz. proxy_server/lib/store.dart PortfolioStore.

create table if not exists portfolio_holdings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  symbol text not null,
  quantity double precision not null,
  cost_basis double precision not null,
  updated_at timestamptz not null default now()
);

create unique index if not exists portfolio_holdings_user_symbol_key
  on portfolio_holdings (user_id, symbol);

alter table portfolio_holdings enable row level security;

drop policy if exists "select own portfolio_holdings" on portfolio_holdings;
create policy "select own portfolio_holdings" on portfolio_holdings
  for select using (auth.uid() = user_id);

drop policy if exists "insert own portfolio_holdings" on portfolio_holdings;
create policy "insert own portfolio_holdings" on portfolio_holdings
  for insert with check (auth.uid() = user_id);

drop policy if exists "update own portfolio_holdings" on portfolio_holdings;
create policy "update own portfolio_holdings" on portfolio_holdings
  for update using (auth.uid() = user_id);

drop policy if exists "delete own portfolio_holdings" on portfolio_holdings;
create policy "delete own portfolio_holdings" on portfolio_holdings
  for delete using (auth.uid() = user_id);
