-- Borsa Takip: çok kullanıcılı geçiş. Supabase Dashboard > SQL Editor'de
-- bir kez çalıştırın (supabase_schema.sql'den SONRA).
-- Mevcut satırların user_id'si NULL kalır; bkz. proje sohbetindeki
-- "sahiplenme" SQL'i (ilk hesabınızı oluşturduktan sonra çalıştırılacak).

-- Composite primary key (user_id, symbol) doğrudan eklenemiyor çünkü bu,
-- user_id'yi NOT NULL yapmayı gerektirir; mevcut 405 satırın user_id'si
-- henüz boş (sahiplenilmemiş). Bunun yerine ayrı bir id sütunu birincil
-- anahtar olur, (user_id, symbol) için NULL'a izin veren bir unique index
-- eklenir (yeni satırlarda user_id her zaman dolu olacağından çakışma
-- kontrolü için yeterli).
alter table watchlist drop constraint if exists watchlist_pkey;
alter table watchlist add column if not exists id bigint generated by default as identity;
alter table watchlist add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table watchlist add primary key (id);
create unique index if not exists watchlist_user_symbol_key on watchlist (user_id, symbol);

alter table notifications add column if not exists user_id uuid references auth.users(id) on delete cascade;
create index if not exists notifications_user_id_idx on notifications (user_id);

-- RLS ikinci savunma katmanı: proxy_server service_role ile çalıştığından
-- bu politikaları zaten baypas eder, asıl erişim kontrolü proxy_server'daki
-- token doğrulamasında yapılır. Politikalar yalnızca anon/public anahtarla
-- doğrudan erişim denenirse devreye girer.
drop policy if exists "select own watchlist" on watchlist;
create policy "select own watchlist" on watchlist
  for select using (auth.uid() = user_id);
drop policy if exists "insert own watchlist" on watchlist;
create policy "insert own watchlist" on watchlist
  for insert with check (auth.uid() = user_id);
drop policy if exists "delete own watchlist" on watchlist;
create policy "delete own watchlist" on watchlist
  for delete using (auth.uid() = user_id);

drop policy if exists "select own notifications" on notifications;
create policy "select own notifications" on notifications
  for select using (auth.uid() = user_id);
drop policy if exists "insert own notifications" on notifications;
create policy "insert own notifications" on notifications
  for insert with check (auth.uid() = user_id);
