-- "Temettü" sekmesinde kullanıcının takip için eklediği semboller.
-- supabase_schema.sql, supabase_schema_auth.sql, supabase_schema_favorites.sql,
-- supabase_schema_technical.sql ve supabase_schema_portfolio.sql'den SONRA,
-- Supabase SQL Editor'de bir kez çalıştırılır. technical_watchlist ile aynı
-- desen: RLS açık, kullanıcı yalnızca kendi satırlarına erişebilir (proxy
-- server_role anahtarıyla zaten RLS'i bypass ediyor, politikalar ekstra
-- güvenlik katmanı olarak duruyor). Bu liste watchlist/favorites/teknik
-- listeden bağımsız: bildirim üretmez, sadece Temettü sekmesinde hangi
-- sembollerin gösterileceğini belirler.

create table if not exists dividend_watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  symbol text not null
);

create unique index if not exists dividend_watchlist_user_symbol_key
  on dividend_watchlist (user_id, symbol);

alter table dividend_watchlist enable row level security;

drop policy if exists "select own dividend_watchlist" on dividend_watchlist;
create policy "select own dividend_watchlist" on dividend_watchlist
  for select using (auth.uid() = user_id);

drop policy if exists "insert own dividend_watchlist" on dividend_watchlist;
create policy "insert own dividend_watchlist" on dividend_watchlist
  for insert with check (auth.uid() = user_id);

drop policy if exists "delete own dividend_watchlist" on dividend_watchlist;
create policy "delete own dividend_watchlist" on dividend_watchlist
  for delete using (auth.uid() = user_id);
