-- "Temel Analiz" sekmesinde kullanıcının analiz için eklediği semboller.
-- supabase_schema.sql, supabase_schema_auth.sql, supabase_schema_favorites.sql,
-- supabase_schema_technical.sql, supabase_schema_portfolio.sql,
-- supabase_schema_dividends.sql ve supabase_schema_fundamentals.sql'den
-- SONRA, Supabase SQL Editor'de bir kez çalıştırılır. technical_watchlist/
-- dividend_watchlist ile aynı desen: RLS açık, kullanıcı yalnızca kendi
-- satırlarına erişebilir (proxy server_role anahtarıyla zaten RLS'i bypass
-- ediyor, politikalar ekstra güvenlik katmanı olarak duruyor). Bu liste
-- watchlist/favorites/teknik/temettü listelerinden bağımsız: bildirim
-- üretmez, sadece Temel Analiz sekmesinde hangi sembollerin gösterileceğini
-- belirler.
--
-- NOT: Bu tablo, supabase_schema_fundamentals.sql'deki stocks/
-- financial_statements/stock_scores tablolarından (herkese açık piyasa
-- verisi, kullanıcı bazlı değil) TAMAMEN FARKLI bir konu — karıştırılmamalı.
--
-- Temel Analiz önceden technical_watchlist'i doğrudan paylaşıyordu (Teknik
-- sekmesine eklenen bir sembol otomatik olarak Temel Analiz'de de
-- görünüyordu); bu iki sekme artık bağımsız. Aşağıdaki bir kerelik
-- kopyalama, geçiş anında mevcut kullanıcıların Temel Analiz'de o an
-- gördüğü sembolleri kaybetmemesi içindir (idempotent — tekrar
-- çalıştırılırsa `on conflict do nothing` sayesinde zarar vermez).

create table if not exists fundamentals_watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  symbol text not null
);

create unique index if not exists fundamentals_watchlist_user_symbol_key
  on fundamentals_watchlist (user_id, symbol);

alter table fundamentals_watchlist enable row level security;

drop policy if exists "select own fundamentals_watchlist" on fundamentals_watchlist;
create policy "select own fundamentals_watchlist" on fundamentals_watchlist
  for select using (auth.uid() = user_id);

drop policy if exists "insert own fundamentals_watchlist" on fundamentals_watchlist;
create policy "insert own fundamentals_watchlist" on fundamentals_watchlist
  for insert with check (auth.uid() = user_id);

drop policy if exists "delete own fundamentals_watchlist" on fundamentals_watchlist;
create policy "delete own fundamentals_watchlist" on fundamentals_watchlist
  for delete using (auth.uid() = user_id);

-- Bir kerelik geçiş: mevcut technical_watchlist satırlarını kopyala.
insert into fundamentals_watchlist (user_id, symbol)
select user_id, symbol from technical_watchlist
on conflict (user_id, symbol) do nothing;
