-- Favoriler ve "aktif takip edilen sembol" tabloları. supabase_schema.sql
-- ve supabase_schema_auth.sql'den SONRA, Supabase SQL Editor'de bir kez
-- çalıştırılır. watchlist/notifications ile aynı desen: RLS açık, sadece
-- kullanıcının kendi satırlarına select/insert/delete izni var (proxy
-- server_role anahtarıyla zaten RLS'i bypass ediyor, politikalar ekstra
-- güvenlik katmanı olarak duruyor).

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  symbol text not null
);

create unique index if not exists favorites_user_symbol_key
  on favorites (user_id, symbol);

alter table favorites enable row level security;

drop policy if exists "select own favorites" on favorites;
create policy "select own favorites" on favorites
  for select using (auth.uid() = user_id);

drop policy if exists "insert own favorites" on favorites;
create policy "insert own favorites" on favorites
  for insert with check (auth.uid() = user_id);

drop policy if exists "delete own favorites" on favorites;
create policy "delete own favorites" on favorites
  for delete using (auth.uid() = user_id);

-- Takip sekmesinde hangi sembolün aktif gösterildiği: kullanıcı başına tek
-- satır (upsert edilir, geçmiş tutulmaz).
create table if not exists tracked_symbol (
  user_id uuid primary key references auth.users(id) on delete cascade,
  symbol text not null,
  updated_at timestamptz not null default now()
);

alter table tracked_symbol enable row level security;

drop policy if exists "select own tracked symbol" on tracked_symbol;
create policy "select own tracked symbol" on tracked_symbol
  for select using (auth.uid() = user_id);

drop policy if exists "insert own tracked symbol" on tracked_symbol;
create policy "insert own tracked symbol" on tracked_symbol
  for insert with check (auth.uid() = user_id);

drop policy if exists "update own tracked symbol" on tracked_symbol;
create policy "update own tracked symbol" on tracked_symbol
  for update using (auth.uid() = user_id);
